/* Project Euler 816 - Shortest distance between points.
 * Closest pair of points via O(n log n) divide and conquer.
 * 2*10^6 points generated by s_{k+1} = s_k^2 mod 50515093, s_0 = 290797.
 */

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

typedef struct { int x, y; int id; } Point;

static long long dist2(const Point *a, const Point *b) {
    long long dx = (long long)a->x - b->x;
    long long dy = (long long)a->y - b->y;
    return dx * dx + dy * dy;
}

static int cmp_x(const void *a, const void *b) {
    const Point *pa = (const Point *)a, *pb = (const Point *)b;
    if (pa->x != pb->x) return pa->x < pb->x ? -1 : 1;
    if (pa->y != pb->y) return pa->y < pb->y ? -1 : 1;
    return 0;
}

static int cmp_y(const void *a, const void *b) {
    const Point *pa = (const Point *)a, *pb = (const Point *)b;
    if (pa->y != pb->y) return pa->y < pb->y ? -1 : 1;
    if (pa->x != pb->x) return pa->x < pb->x ? -1 : 1;
    return 0;
}

static long long brute(Point *pts, int n) {
    long long best = -1;
    for (int i = 0; i < n; i++)
        for (int j = i + 1; j < n; j++) {
            long long d = dist2(&pts[i], &pts[j]);
            if (best < 0 || d < best) best = d;
        }
    return best;
}

static Point *tempbuf;

static long long closest_rec(Point *X, int lo, int hi, Point *Y, int yn) {
    int n = hi - lo + 1;
    if (n <= 3) {
        /* Sort X[lo..hi] by y into Y (insertion sort). */
        for (int i = 0; i < n; i++) Y[i] = X[lo + i];
        for (int i = 1; i < n; i++) {
            Point key = Y[i];
            int j = i - 1;
            while (j >= 0 && Y[j].y > key.y) { Y[j + 1] = Y[j]; j--; }
            Y[j + 1] = key;
        }
        return brute(X + lo, n);
    }

    int mid = lo + n / 2;
    int midx = X[mid - 1].x;

    /* Split Y (y-sorted) into YL [id < mid] and YR [id >= mid], both y-sorted.
       Two-pass to avoid nl shifting during accumulation. */
    int nl = 0, nr = 0;
    for (int i = 0; i < yn; i++)
        if (Y[i].id < mid) tempbuf[nl++] = Y[i];
    for (int i = 0; i < yn; i++)
        if (Y[i].id >= mid) tempbuf[nl + nr++] = Y[i];
    memcpy(Y, tempbuf, (size_t)yn * sizeof(Point));

    long long dl = closest_rec(X, lo, mid - 1, Y, nl);
    long long dr = closest_rec(X, mid, hi, Y + nl, nr);
    long long d = dl < dr ? dl : dr;

    /* Merge Y[0..nl-1] and Y[nl..yn-1] (both y-sorted) back into y-order. */
    {
        int i = 0, j = 0, k = 0;
        while (i < nl && j < nr) {
            if (Y[i].y <= Y[nl + j].y) tempbuf[k++] = Y[i++];
            else tempbuf[k++] = Y[nl + j++];
        }
        while (i < nl) tempbuf[k++] = Y[i++];
        while (j < nr) tempbuf[k++] = Y[nl + j++];
        memcpy(Y, tempbuf, (size_t)yn * sizeof(Point));
    }

    /* Build strip from Y (y-sorted): points within sqrt(d) of midx. */
    int sc = 0;
    for (int i = 0; i < yn; i++) {
        long long dx = (long long)Y[i].x - midx;
        if (dx * dx < d) tempbuf[sc++] = Y[i];
    }
    for (int i = 0; i < sc; i++) {
        for (int j = i + 1; j < sc; j++) {
            long long dy = (long long)tempbuf[j].y - tempbuf[i].y;
            if (dy * dy >= d) break;
            long long dd = dist2(&tempbuf[i], &tempbuf[j]);
            if (dd < d) d = dd;
        }
    }
    return d;
}

double p816_native(void) {
    const int N = 2000000;
    Point *X = (Point *)malloc((size_t)N * sizeof(Point));
    Point *Y = (Point *)malloc((size_t)N * sizeof(Point));
    tempbuf = (Point *)malloc((size_t)N * sizeof(Point));
    if (!X || !Y || !tempbuf) return -1.0;

    /* Generate points (s_{2i}, s_{2i+1}) where s_0=290797, s_{k+1}=s_k^2 mod 50515093. */
    long long s = 290797;
    const long long M = 50515093;
    for (int i = 0; i < N; i++) {
        long long s0 = s;
        long long s1 = (s0 * s0) % M;
        X[i].x = (int)s0;
        X[i].y = (int)s1;
        s = (s1 * s1) % M;  /* advance to s_{2i+2} */
    }

    qsort(X, (size_t)N, sizeof(Point), cmp_x);
    for (int i = 0; i < N; i++) X[i].id = i;
    memcpy(Y, X, (size_t)N * sizeof(Point));
    qsort(Y, (size_t)N, sizeof(Point), cmp_y);

    long long d2 = closest_rec(X, 0, N - 1, Y, N);

    free(X);
    free(Y);
    free(tempbuf);
    return sqrt((double)d2);
}
