/* Project Euler 941: de Bruijn's Combination Lock.
 *
 * Compute F(N) = sum_{i=1..N} i * a_sorted[i-1] mod 1234567891,
 * where a_1..a_N are generated by an LCG, each a_i is treated as a
 * 12-digit string, ranked by its first-occurrence position in the
 * lexicographically smallest de Bruijn sequence C(10,12), and then
 * sorted by that rank.
 *
 * The ranking uses the RankDB algorithm from Sawada & Williams,
 * specialized to k=10, n=12.
 *
 * Ported from the Python reference solver.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define ND 12   /* word length */
#define KK 10   /* alphabet size (digits 0..9 mapped to 1..10) */
#define MOD_LCG 1000000000000ULL  /* 10^12 */

static long long power_arr[ND + 1];

/* Scratch arrays for rank_db / T (reused across calls) */
static int t_neck[ND + 1];
static int neck_rep_arr[ND + 1];
static int prev_arr[ND + 1];
static long long B_arr[ND + 1][ND + 1];
static int suf_arr[ND + 1][ND + 1];

/* 4-digit lookup table for fast base-10 decomposition */
static int digits4[10000][4];

static void init_tables(void) {
    power_arr[0] = 1;
    for (int i = 1; i <= ND; i++)
        power_arr[i] = power_arr[i - 1] * KK;
    for (int x = 0; x < 10000; x++) {
        digits4[x][0] = x / 1000 + 1;
        digits4[x][1] = (x / 100) % 10 + 1;
        digits4[x][2] = (x / 10) % 10 + 1;
        digits4[x][3] = x % 10 + 1;
    }
}

/* Length of the longest Lyndon prefix of w[1..ND]. */
static int lyn(const int *w) {
    int p = 1;
    for (int i = 2; i <= ND; i++) {
        if (w[i] < w[i - p]) return p;
        if (w[i] > w[i - p]) p = i;
    }
    return p;
}

/* True iff w[1..ND] is a necklace (lexicographically smallest rotation). */
static int is_necklace(const int *w) {
    int p = 1;
    for (int i = 2; i <= ND; i++) {
        if (w[i] < w[i - p]) return 0;
        if (w[i] > w[i - p]) p = i;
    }
    return (ND % p) == 0;
}

/* out[1..ND] = largest necklace <= w[1..ND]. */
static void largest_necklace(const int *w, int *out) {
    for (int i = 1; i <= ND; i++) out[i] = w[i];
    while (!is_necklace(out)) {
        int p = lyn(out);
        out[p] -= 1;
        for (int i = p + 1; i <= ND; i++) out[i] = KK;
    }
}

/* Number of strings whose necklace is <= w[1..ND]. */
static long long T_func(const int *w) {
    largest_necklace(w, t_neck);

    B_arr[0][0] = 1;
    for (int t = 1; t <= ND; t++) {
        B_arr[t][t] = 0;
        for (int j = t - 1; j >= 0; j--)
            B_arr[t][j] = B_arr[t][j + 1]
                        + (KK - t_neck[j + 1]) * B_arr[t - j - 1][0];
    }

    for (int i = 2; i <= ND; i++) {
        int sv = i;
        for (int j = i; j <= ND; j++) {
            if (t_neck[j] > t_neck[j - sv + 1]) sv = j + 1;
            suf_arr[i][j] = j - sv + 1;
        }
    }

    long long tot = lyn(t_neck);
    for (int t = 1; t <= ND; t++) {
        long long b0 = B_arr[t - 1][0];
        for (int j = 0; j < ND; j++) {
            if (j + t <= ND) {
                tot += b0 * (t_neck[j + 1] - 1) * power_arr[ND - t - j];
            } else {
                int sfx;
                if (j < ND - t + 2) sfx = 0;
                else sfx = suf_arr[ND - t + 2][j];
                if (t_neck[j + 1] > t_neck[sfx + 1]) {
                    tot += B_arr[ND - j + sfx][sfx + 1]
                         + (t_neck[j + 1] - t_neck[sfx + 1] - 1)
                           * B_arr[ND - j - 1][0];
                }
            }
        }
    }
    return tot;
}

/* 1-based rank (start position) of w in the linearized lex-smallest
 * de Bruijn sequence DB(ND, KK).
 *
 * The recursion in the Python original always lands on a necklace
 * (which returns immediately via the is_necklace branch), so we
 * inline that case and avoid recursion entirely.
 */
static long long rank_db(const int *w) {
    /* Wraparound case: w = KK^t 1^(ND-t) for t >= 1 */
    int t = 0;
    while (t < ND && w[t + 1] == KK) t++;
    int j = t;
    while (j < ND && w[j + 1] == 1) j++;
    if (t >= 1 && j == ND)
        return power_arr[ND] - t + 1;

    /* If w is already a necklace, done */
    if (is_necklace(w))
        return 1 - lyn(w) + T_func(w);

    /* Find the necklace representative by rotation */
    for (int i = 1; i <= ND; i++) neck_rep_arr[i] = w[i];
    int s = 0;
    while (!is_necklace(neck_rep_arr)) {
        s++;
        for (int i = 1; i <= ND; i++) {
            int j2 = i + s;
            neck_rep_arr[i] = (j2 <= ND) ? w[j2] : w[j2 - ND];
        }
    }

    /* neck_rep_arr is now a necklace (not a wraparound case) */
    int lyn_nr = lyn(neck_rep_arr);
    if (s != t)
        return 1 + T_func(neck_rep_arr) - s;
    if (lyn_nr < ND)
        return 1 - lyn_nr + T_func(neck_rep_arr) - s;

    /* Adjust suffix to 1s, move to previous necklace */
    for (int i = ND - s + 1; i <= ND; i++) neck_rep_arr[i] = 1;
    largest_necklace(neck_rep_arr, prev_arr);
    return 1 + T_func(prev_arr) - s;
}

/* Convert a 12-digit integer to symbols 1..10 in w[1..12]. */
static void int_to_word12(uint64_t x, int *w) {
    uint64_t hi = x / 100000000ULL;        /* top 4 digits */
    uint64_t mid = (x / 10000ULL) % 10000ULL;  /* middle 4 */
    uint64_t lo = x % 10000ULL;            /* bottom 4 */
    const int *d0 = digits4[hi];
    const int *d1 = digits4[mid];
    const int *d2 = digits4[lo];
    w[1] = d0[0]; w[2] = d0[1]; w[3] = d0[2]; w[4] = d0[3];
    w[5] = d1[0]; w[6] = d1[1]; w[7] = d1[2]; w[8] = d1[3];
    w[9] = d2[0]; w[10] = d2[1]; w[11] = d2[2]; w[12] = d2[3];
}

static int counts_buf[65536];

/* Compute F(N) mod `mod` using LSD radix sort (3 passes of 16 bits). */
static uint64_t compute_F_mod(uint64_t N, uint64_t mod) {
    uint64_t *keys = malloc(N * sizeof(uint64_t));
    uint64_t *vals = malloc(N * sizeof(uint64_t));
    uint64_t *tmp_k = malloc(N * sizeof(uint64_t));
    uint64_t *tmp_v = malloc(N * sizeof(uint64_t));
    if (!keys || !vals || !tmp_k || !tmp_v) {
        fprintf(stderr, "out of memory\n");
        exit(1);
    }

    int w[ND + 1];
    uint64_t a = 0;
    for (uint64_t i = 0; i < N; i++) {
        a = (920461ULL * a + 800217387569ULL) % MOD_LCG;
        int_to_word12(a, w);
        keys[i] = (uint64_t)rank_db(w);
        vals[i] = a;
    }

    uint64_t *sk = keys, *dk = tmp_k;
    uint64_t *svar = vals, *dvar = tmp_v;

    for (int pass = 0; pass < 3; pass++) {
        int shift = pass * 16;
        memset(counts_buf, 0, sizeof(counts_buf));
        for (uint64_t i = 0; i < N; i++)
            counts_buf[(sk[i] >> shift) & 0xFFFF]++;
        int total = 0;
        for (int b = 0; b < 65536; b++) {
            int c = counts_buf[b];
            counts_buf[b] = total;
            total += c;
        }
        for (uint64_t i = 0; i < N; i++) {
            int b = (sk[i] >> shift) & 0xFFFF;
            int p = counts_buf[b]++;
            dk[p] = sk[i];
            dvar[p] = svar[i];
        }
        uint64_t *tk = sk; sk = dk; dk = tk;
        uint64_t *tv = svar; svar = dvar; dvar = tv;
    }

    /* After 3 passes (odd), sorted data is in sk / svar */
    uint64_t acc = 0;
    for (uint64_t i = 0; i < N; i++)
        acc = (acc + (i + 1) * (svar[i] % mod)) % mod;

    free(keys); free(vals); free(tmp_k); free(tmp_v);
    return acc;
}

long long p941_native(void) {
    init_tables();

    /* Self-tests from the problem statement */
    if (compute_F_mod(2, UINT64_MAX) != 2194210461325ULL) {
        fprintf(stderr, "p941 self-test 1 failed\n");
        return -1;
    }
    if (compute_F_mod(10, UINT64_MAX) != 32698850376317ULL) {
        fprintf(stderr, "p941 self-test 2 failed\n");
        return -1;
    }

    return (long long)compute_F_mod(10000000ULL, 1234567891ULL);
}
